# main
spring:
  jpa:
    hibernate:
      ddl-auto: create
  docker:
    compose:
      lifecycle-management: start_only
  graphql:
    graphiql:
      enabled: true
logging:
  level:
    org.springframework.boot.autoconfigure.logging: ERROR